#!/usr/bin/env python3
"""
Phase 4 page generator: insights index, 6 articles, about and contact.
Reuses the page() helper from generate_phase3.py.

Run: python3 _build/generate_phase4.py
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "_build"))
from generate_phase3 import page, write, ICONS  # noqa: E402


# ---------- Insight articles -----------------------------------------------

ARTICLES = [
    {
        "slug": "insights/proof-of-purchase-mechanics",
        "title": "Receipts, batch codes, unique codes: which proof-of-purchase mechanic actually works?",
        "desc": "A balanced look at the four common proof-of-purchase mechanics for FMCG promotions — what they involve, how they fail, the impact each has on data quality, and why a unique code is the only mechanic that meets the bar.",
        "chip": "Proof of purchase",
        "date": "2026-04-30",
        "date_human": "30 April 2026",
        "read_time": "8 min read",
        "summary": "Till receipts are easily faked. Batch codes provide no real security and corrupt your consumer database with bot- and farm-driven entries. A unique code is the only mechanic that can be enforced as single-use, audited end-to-end, never sits in a database that could leak, and produces clean consumer data. Here&rsquo;s the comparison in full.",
        "body": """
          <p>Every promotion involving a reward, a prize, a refund or a loyalty point needs a way to verify a real purchase happened. The mechanic the brand picks decides three things: how secure the campaign is, how easily it can be audited, and how much fraud the brand will absorb. Get the choice wrong and a campaign can lose its commercial value before it even runs.</p>
          <p>Yet the choice is most often made by default rather than design. Around 90% of European on-pack promotions still use batch codes &mdash; the weakest mechanic on the list &mdash; because unique codes have historically been seen as complex and expensive to print. That has changed. Here&rsquo;s the four-mechanic landscape, side by side.</p>

          <h2>No verification</h2>
          <p>Free-entry sweepstakes and shelf-scanning mechanics with no proof-of-purchase requirement at all. Cheap and frictionless for the consumer. Hopeless against bots, account farms and incentive abuse. Fine for low-value, data-light campaigns where the brand cares about reach more than rigour. Inappropriate for anything with monetary value attached &mdash; and the consumer database it produces is mostly noise.</p>

          <h2>Till receipts</h2>
          <p>The original proof-of-purchase mechanic, designed for human inspection in a different era. Receipts are trivially faked: edited in image software, generated by free online tools, photographed from another consumer&rsquo;s shopping. Auditing receipts at scale requires either expensive manual review or imperfect machine OCR; audit trails are partial at best. The consumer friction is real &mdash; people have to keep, photograph and upload them &mdash; and it depresses participation rates among the audiences brands want most. The friction filters some bots, but motivated fraudsters still produce fakes that pass automated checks.</p>

          <h2>Batch codes</h2>
          <p>The same code printed on every pack of an SKU. There is no way to enforce single use, because every pack carries the same code; once one consumer enters it, anyone can reuse it indefinitely. Limiting entries per account doesn&rsquo;t fix the problem &mdash; bots and fraudsters simply create more accounts. As a security mechanism, batch codes provide essentially no protection. They are still the most common mechanic in European on-pack promotions, almost entirely for historical cost reasons.</p>
          <p>The downstream cost lands on the data. Because anyone can spin up endless fake accounts and reuse the same code, the consumer records you accumulate are heavily contaminated &mdash; bots, duplicates, throwaway emails &mdash; which inflates campaign statistics, distorts ROI measurement, makes follow-up activity less effective, and creates GDPR overhead for records that shouldn&rsquo;t exist in the first place.</p>

          <h2>Unique codes</h2>
          <p>Every pack carries its own unguessable, non-sequential code. Each code can only be used once, by one consumer, ever &mdash; enforcement happens at the system level rather than as a policy you have to police. Every entry is logged with a full audit trail. Each code can be cross-referenced against the consumer record, the SKU, the production date and the production line, and that cross-reference is itself a layer of fraud detection. Behavioural risk-scoring of consumers, combined with the audit trail, gives campaign-level statistics that are actually meaningful.</p>
          <p>The data quality follows directly. A fake account can&rsquo;t enter a code it doesn&rsquo;t physically have, so the consumer database a unique-code campaign produces is essentially self-cleaning &mdash; every record corresponds to a real person who made a real purchase. That makes the data genuinely useful for follow-up activity, personalised mechanics, lifetime-value modelling and ROI measurement, and dramatically lowers the GDPR overhead of holding records you wouldn&rsquo;t have wanted in the first place.</p>

          <div class="callout">
            <p><strong>The architectural advantage few people talk about.</strong> If a unique-code platform stores its issued codes in a database, that database is itself a target. Hive IP&rsquo;s platform is closed-loop and algorithmic &mdash; codes are never stored on the in-factory ACG and are never held in a list that could leak. Validation reverse-engineers each submitted code rather than looking it up. The systemic security risk that has compromised entire campaigns at competing providers doesn&rsquo;t exist in this architecture.</p>
          </div>

          <h2>The takeaway</h2>
          <p>For any promotion with monetary value attached &mdash; cash back, prizes, vouchers worth pursuing, refunds, anti-counterfeit verification &mdash; a unique code is the right primitive. Till receipts and batch codes have edge-case roles, but the default has shifted, and the brands that still use the older mechanics are usually doing so for historical reasons rather than current technical or commercial constraints. <a href="../../why-unique-codes/">Read the full proof-of-purchase argument &rarr;</a></p>
        """,
    },
    {
        "slug": "insights/in-factory-printing-cheaper",
        "title": "Why in-factory unique-code printing can save 78% or more",
        "desc": "The legacy approach charges per coded pack regardless of whether the codes form part of any campaign. In-factory printing flips that model — pay only on the codes covered by an active promotion — and the savings compound with every additional campaign.",
        "chip": "Cost &amp; commercial",
        "date": "2026-04-22",
        "date_human": "22 April 2026",
        "read_time": "6 min read",
        "summary": "The legacy packaging-supplier model charges £3,000&ndash;£5,000 per million coded packs whether or not those codes form part of any campaign. In-factory printing flips it: pay only on the codes covered by an active promotion. The savings compound every time you launch another campaign.",
        "body": """
          <p>For decades, the standard way to apply unique codes to FMCG packs has been to send the artwork to a packaging supplier and pay them to print the codes during the production run. That model is still in widespread use today, and it carries a few well-known limitations.</p>

          <h2>The headline cost</h2>
          <p>Packaging suppliers typically charge between &pound;3,000 and &pound;5,000 per million coded packs &mdash; a publicly-known industry rate range. For a programme that runs 50 million coded packs a year, that&rsquo;s &pound;150,000 to &pound;250,000 in print fees alone, before any of the validation, security or marketing infrastructure that turns those codes into a campaign.</p>
          <p>And critically, this fee is charged on every coded pack, whether or not those codes ever form part of a live promotion. A campaign that under-runs &mdash; or that needs to be cancelled because the timing doesn&rsquo;t work &mdash; carries the full print bill regardless.</p>

          <h2>What changes with in-factory</h2>
          <p>Hive IP&rsquo;s ACG <em>(Automated Code Generator)</em> is a small device that plugs into the existing Best Before Date printer on each production line. When the BBD printer requests a code, the ACG generates a unique, non-sequential code on the fly and transmits it to the printer, which prints it alongside the BBD on the outside of the pack.</p>
          <p>Three things change:</p>
          <ol>
            <li><strong>The hardware is supplied at no charge.</strong> No capital cost, no licence per unit, no ongoing rental fee for the unit itself.</li>
            <li><strong>The codes themselves cost nothing to print.</strong> Whatever your annual production volume, every pack can carry a code with no marginal print fee.</li>
            <li><strong>Billing is on the codes covered by an active campaign.</strong> You pay only on the codes that are in market during a live promotional window &mdash; at a per-million rate that&rsquo;s a fraction of what the legacy supplier route charges.</li>
          </ol>

          <p>A worked example. A brand produces 120 million packs per year, with every pack carrying a code (10 million per month). They run a single 2-month promotion. The codes on the 20 million packs in market during those 2 months are billed. The remaining 100 million coded packs that year cost nothing. Run a second 2-month promotion later in the year and you&rsquo;d pay on a further 20 million &mdash; total billed: 40 million from a 120 million annual production.</p>

          <h2>Why the savings compound</h2>
          <p>Once the hardware is in place and the line is running, the marginal cost of running another campaign through the same set-up is much lower than it would be on the legacy model. A second campaign in the same year &mdash; or a third, or a fourth &mdash; only incurs the usage fee on the codes covered by that campaign window. The set-up cost is sunk. Customers running multiple promotions per year typically save <strong>78% or more</strong> against the legacy supplier route, with deeper savings reached by brands that run high-volume programmes consistently.</p>

          <h2>The hidden cost of the legacy approach</h2>
          <p>The cash savings are the headline, but they aren&rsquo;t the whole story. The legacy approach also costs in two less obvious ways:</p>
          <ul>
            <li><strong>Time.</strong> The artwork-to-shelf cycle for a unique-coded run takes months. Missed sponsorship moments, missed sport, missed seasonal opportunities &mdash; all of which have a real commercial cost that doesn&rsquo;t appear on the print invoice.</li>
            <li><strong>Optionality.</strong> Because every print run is committed in advance, marketing teams plan campaigns around the print cycle rather than around opportunities. The number of campaigns a brand runs per year is limited by the operational tax of running them, not by the marketing imagination.</li>
          </ul>

          <h2>The takeaway</h2>
          <p>Cost is the most legible way to compare in-factory and packaging-supplier print, and the in-factory case wins on cost cleanly. But the operational and strategic upside &mdash; days-not-months campaign launches, optionality on what to run and when &mdash; is often the bigger long-run prize. <a href="../../why-in-factory/">Read the full case for in-factory printing &rarr;</a></p>
        """,
    },
    {
        "slug": "insights/closed-loop-validation",
        "title": "Closed-loop coding: why algorithmic validation beats database lookup",
        "desc": "Database lookup is a poor fit for validating random, non-sequential pack codes at scale. Algorithmic validation is faster, more scalable and removes the master-code database risk.",
        "chip": "Architecture &amp; security",
        "date": "2026-04-15",
        "date_human": "15 April 2026",
        "read_time": "5 min read",
        "summary": "Most code-validation platforms store every issued code in a database and check submissions against it. For random, non-sequential pack codes at FMCG scale, that creates lookup bottlenecks and a security concentration risk. Algorithmic validation is faster, more scalable, and removes the master-code database risk.",
        "body": """
          <p>If you were designing a unique-code validation system from scratch, the obvious approach would be to store every issued code in a database, attach metadata to each one, and check incoming submissions against that table. It&rsquo;s simple, it&rsquo;s familiar, and it&rsquo;s how most code-validation platforms work in practice.</p>
          <p>But for random, non-sequential pack codes at FMCG scale, database lookup is the wrong primitive. It creates both a performance bottleneck and a security concentration risk.</p>

          <h2>What the database approach looks like</h2>
          <p>In a database-lookup system, every code that&rsquo;s ever been issued &mdash; on a pack, in a campaign, ready to redeem &mdash; sits in a table with associated metadata. Validation is a lookup: find the code, check whether it&rsquo;s been used, return the result.</p>
          <p>That sounds clean until the codes are truly random. With random, non-sequential codes, you cannot rely on neat sequential ranges or compact index shortcuts. Every validation still has to interrogate a very large store of issued codes, and that store grows with every pack ever produced.</p>
          <p>There is also the security catch: it puts every issued code in one place. That place is then a target. A breach of the database is a breach of the entire campaign &mdash; potentially every code on every pack on every shelf, exposed at once.</p>

          <h2>What closed-loop algorithmic validation looks like</h2>
          <p>Hive IP&rsquo;s validation system works differently. Codes are generated algorithmically using a multi-cipher proprietary algorithm. Each code carries enough information to be reverse-engineered against an &ldquo;allocation&rdquo; &mdash; a logical grouping of codes that share properties such as market, SKU and production line. Validation reverses the algorithm to check whether the submitted code is real, whether it belongs to the active allocation, and whether it&rsquo;s been used before.</p>
          <p>That makes validation faster and much more scalable: the system is validating the structure and allocation of the submitted code, not searching a master list of every code that could exist.</p>
          <p>What this means in practice:</p>
          <ul>
            <li>There is no master list of issued codes.</li>
            <li>Codes are not stored on the in-factory ACG &mdash; only the algorithm is.</li>
            <li>The cloud validation service maintains an audit log of entries (which is well-protected) but not a master inventory of issuable codes.</li>
            <li>A breach of the validation system can&rsquo;t expose codes that haven&rsquo;t been issued, because they don&rsquo;t exist as data anywhere.</li>
          </ul>

          <div class="callout">
            <p><strong>The asymmetry that matters.</strong> A breach of an issued-codes database compromises codes <em>before they&rsquo;ve been used</em> &mdash; meaning attackers can redeem rewards meant for legitimate consumers. A closed-loop architecture removes this attack surface entirely. Codes that haven&rsquo;t been used are not stored anywhere.</p>
          </div>

          <h2>What it costs you</h2>
          <p>The trade-off is real but small. Algorithmic validation requires careful key management and a tight relationship between the generation algorithm and the validation algorithm. There&rsquo;s no &ldquo;just look it up&rdquo; fallback if something goes wrong; the algorithm has to be right. In practice, this is a one-time engineering investment, not an ongoing operational tax.</p>

          <h2>The takeaway</h2>
          <p>For any high-value or high-profile campaign, the database-lookup architecture is a structural risk and a scale limitation you don&rsquo;t need to take. Closed-loop algorithmic validation isn&rsquo;t a marginal optimisation &mdash; it&rsquo;s a different posture on speed, scale and what kinds of breach are possible at all. <a href="../../solution/validation/">Read about Hive IP&rsquo;s cloud validation &rarr;</a></p>
        """,
    },
    {
        "slug": "insights/outside-vs-inside-pack-code-copying",
        "title": "Outside vs inside the pack: an honest answer on code copying",
        "desc": "The most common objection to printing unique codes outside the pack is fraud — specifically, in-store code copying. The answer, layered: most consumers don&rsquo;t copy codes, AI Vision can audit the rare in-store concern when needed, and the engagement gains more than cover the residual fraud.",
        "chip": "Fraud audit",
        "date": "2026-04-08",
        "date_human": "8 April 2026",
        "read_time": "6 min read",
        "summary": "&ldquo;If the code is on the outside of the pack, can&rsquo;t people copy it in the shop?&rdquo; It&rsquo;s the most common objection to in-factory printing. Here&rsquo;s the layered answer &mdash; with campaign data, optional AI Vision audit checks, and an honest comparison of the cost of residual fraud against the engagement gains.",
        "body": """
          <p>The most common question we hear when we explain in-factory unique-code printing &mdash; where the code goes on the outside of the pack alongside the Best Before Date &mdash; is some version of <em>&ldquo;can&rsquo;t people just copy that in the shop?&rdquo;</em>. It&rsquo;s a fair question. It&rsquo;s also one we measure on every campaign, and the answer is layered.</p>

          <h2>Most consumers don&rsquo;t copy codes</h2>
          <p>The overall incidence of code-copying on prize draws and point-collection schemes is statistically tiny relative to legitimate entries. We measure it on every campaign and report it back to the brand. The premise that outside-the-pack codes get copied at any meaningful scale is, in practice, not borne out by the data.</p>

          <h2>There are two types &mdash; only one is solved by hiding the code</h2>
          <p>It helps to distinguish two patterns:</p>
          <ul>
            <li><strong>Type 1: in-store copying.</strong> Someone scans or photographs the code without buying the product. This is what hiding the code on the inside of the pack is meant to prevent.</li>
            <li><strong>Type 2: sharing.</strong> A legitimate buyer gives the code to a friend or family member who tries to use it. This happens regardless of where on the pack the code is printed.</li>
          </ul>
          <p>Type 2 is by far the more common type, and Type 2 isn&rsquo;t prevented by inside-the-pack printing. So the protective effect of hiding the code is smaller than it seems.</p>

          <h2>AI Vision can audit the rare in-store copying concern</h2>
          <p>For the residual Type 1 risk, recent AI Vision advances make an extra audit layer feasible. When a code is submitted, the campaign flow can ask the user to scan the code and surrounding environment so the campaign can check they are not standing in-store. The same scan can capture the BBD and production-line data for cross-reference against the code itself. This can be applied universally, or triggered selectively when a consumer&rsquo;s behaviour pattern looks suspicious.</p>

          <h2>A measure-retain-audit framework backstops the rest</h2>
          <p>For higher-stakes promotions &mdash; prize draws with monetary value &mdash; winners can be required to retain their physical pack and produce it on request. Audits are typically only triggered on participants who have won something of real value, or who have breached a risk-score threshold &mdash; so the operational overhead is small.</p>

          <h2>The advantages of outside-the-pack more than cover the residual fraud</h2>
          <p>Putting the code on the outside of the pack delivers benefits that compound across every interaction:</p>
          <ul>
            <li>No need to rip open packaging to find the code.</li>
            <li>Faster, easier mobile scanning.</li>
            <li>On-the-go participation is possible during commutes, breaks and impulse moments.</li>
            <li>No risk of consumers tearing open the product in store.</li>
          </ul>
          <p>These translate into measurably higher engagement rates &mdash; which is, after all, the entire point of running the campaign.</p>

          <h2>The takeaway</h2>
          <p>For the vast majority of promotions, printing on the outside of the pack is the right answer. For the small set of campaigns where the brand judges the risk profile differently, an inside-pack route is available &mdash; we offer that too. <a href="../../why-in-factory/#code-copying">See the full code-copying argument on the Why-in-factory page &rarr;</a></p>
        """,
    },
    {
        "slug": "insights/agile-digital-promotions",
        "title": "From on-pack to digital: how to run agile, just-in-time promotions",
        "desc": "When every pack already carries a unique code, marketing teams stop planning around the print cycle and start planning around the moment. A note on what that actually unlocks in practice.",
        "chip": "Marketing strategy",
        "date": "2026-03-30",
        "date_human": "30 March 2026",
        "read_time": "5 min read",
        "summary": "When every pack already carries a unique code, marketing teams stop planning around the print cycle and start planning around the moment. A field note on what that unlocks in practice &mdash; and how to think about the marketing operating model that takes advantage of it.",
        "body": """
          <p>The strategic upside of unique-code printing isn&rsquo;t cost. It&rsquo;s tempo.</p>
          <p>If your packs only carry codes during specific promotional runs, you plan campaigns around the printing window. You decide what to run two quarters out. You commit print volume and design before you know what&rsquo;s happening in the world. By the time the packs are on the shelf, the moment that motivated the campaign may have passed.</p>
          <p>If every pack carries a code, all the time, that constraint dissolves.</p>

          <h2>What &ldquo;always promotionally ready&rdquo; actually means</h2>
          <p>It means three things you can do that you couldn&rsquo;t before.</p>

          <h3>1. React to live events</h3>
          <p>A sponsored athlete wins. A sporting moment captures the public mood. A weather pattern makes one of your products suddenly relevant. A competitor moves and you want to respond before the news cycle moves on. With every pack already coded, you can launch a digital direct-to-consumer push within minutes of the trigger &mdash; no print run, no supply chain, no waiting.</p>

          <h3>2. Test before you commit</h3>
          <p>Run a regional pilot in one market or store cluster before going national. The codes are already there; the validation infrastructure is already running; the agency&rsquo;s API integration is already done. The only new asset you&rsquo;re building is the consumer-facing experience for the test.</p>

          <h3>3. Personalise at the per-pack level</h3>
          <p>Because each code is unique to a pack and tied to a consumer when entered, you can run mechanics that depend on per-consumer history &mdash; rewarding repeat buyers differently, surfacing relevant offers based on what a household already buys, building lifetime-value programmes that reflect actual purchase behaviour.</p>

          <h2>The marketing operating model that takes advantage</h2>
          <p>There&rsquo;s a temptation to treat always-on coding as a cost saving and otherwise carry on as before. That misses most of the value. Brands that get the most out of always-on coding tend to make a few operating-model shifts:</p>
          <ul>
            <li><strong>Reserve a portion of the marketing calendar for live, reactive activations.</strong> Don&rsquo;t plan every campaign quarters out; leave room.</li>
            <li><strong>Pre-build templates and creative assets</strong> for common reactive scenarios (sport, weather, sponsorship moments) so launching takes minutes rather than days.</li>
            <li><strong>Bring agency, validation and consumer-support teams into the same operating rhythm</strong> &mdash; agile activations require the whole stack to move together.</li>
          </ul>

          <h2>The takeaway</h2>
          <p>Always-on coding is a tempo lever, not a cost lever. The brands that treat it as the latter only get a fraction of the value. The ones that treat it as a tempo shift in how marketing actually operates &mdash; that&rsquo;s where the compounding returns live. <a href="../../our-model/">Read about our always-on commercial model &rarr;</a></p>
        """,
    },
    {
        "slug": "insights/beyond-promotions-five-uses",
        "title": "Beyond promotions: five other things unique codes unlock",
        "desc": "Unique codes started life as a promotional mechanic. Today, the same per-pack identifier can underpin loyalty, anti-counterfeiting, traceability, provenance and consumer support — all from one data layer.",
        "chip": "Applications",
        "date": "2026-03-20",
        "date_human": "20 March 2026",
        "read_time": "5 min read",
        "summary": "Unique codes started life as a promotional mechanic. The same per-pack identifier &mdash; once you&rsquo;re printing it on every pack &mdash; can underpin loyalty, anti-counterfeiting, traceability, provenance and consumer support. Five applications worth thinking about.",
        "body": """
          <p>The conversation about unique codes is usually a conversation about promotions. That&rsquo;s where the mechanic started, and it&rsquo;s where most of the case studies live. But once you&rsquo;re printing a unique code on every pack, the per-pack identifier becomes a foundation for several other applications that don&rsquo;t require any incremental investment in printing &mdash; only in the consumer-facing or operational experience that surfaces the value.</p>

          <h2>1. Loyalty programmes that reward real purchases</h2>
          <p>A loyalty programme is only as good as its proof. Unique codes turn every pack into an authenticated proof-of-purchase event &mdash; the foundation of any meaningful multi-purchase or points-based mechanic. News UK&rsquo;s Sun Saver programme runs on this model.</p>

          <h2>2. Anti-counterfeiting and brand protection</h2>
          <p>Each pack carries a digital signature. Codes that don&rsquo;t validate are themselves a signal &mdash; patterns of failed validations across geographies and time can pinpoint counterfeit activity in specific markets. For brands operating in markets where counterfeiting is a known risk, the anti-counterfeit application can run alongside a promotional or loyalty programme on the same codes &mdash; meaning the brand-protection value is essentially free, because the same per-pack identifier serves both jobs.</p>

          <h2>3. Supply-chain traceability and recall</h2>
          <p>A per-pack identifier captured at the moment of production lets internal teams look up production date, line, batch and SKU for any individual unit. The granularity that makes targeted recall, complaint investigation and quality forensics actually possible.</p>

          <h2>4. Provenance and sustainability stories</h2>
          <p>Use the per-pack code to link consumers to provenance data, ingredient origin, carbon-footprint information, or any sustainability-credential proof point that matters to your category. Premium and provenance-led categories are especially well-served &mdash; consumers can scan a pack and see content tailored to that specific unit, not the generic SKU.</p>

          <h2>5. Consumer support</h2>
          <p>When a consumer raises a query &mdash; <em>my code didn&rsquo;t work, my pack was damaged, can I have a replacement</em> &mdash; the support team can look up the code, see its full history, validate the consumer&rsquo;s account, and resolve the query in under a minute. The per-pack identifier turns support from guesswork into evidence-led problem-solving.</p>

          <div class="callout">
            <p><strong>The strategic implication.</strong> Once you&rsquo;re coding every pack, the per-pack identifier is a strategic data layer for the business, not a per-campaign expense. Treat it as such, and the return on the original print investment compounds across every team that learns to use it.</p>
          </div>

          <h2>The takeaway</h2>
          <p>The strongest argument for always-on coding isn&rsquo;t any single application &mdash; it&rsquo;s the optionality of having all of them available without further hardware investment. <a href="../../applications/">Browse all applications &rarr;</a></p>
        """,
    },
]


def article_body(a, prev_next):
    prev_a, next_a = prev_next
    other_articles = ""
    if prev_a or next_a:
        items = []
        if next_a:
            items.append(f'<a href="../{next_a["slug"].split("/")[-1]}/" class="card"><span class="card__cta" style="margin-bottom: 0.5rem;">Next article &rarr;</span><h3 style="margin: 0;">{next_a["title"]}</h3></a>')
        if prev_a:
            items.append(f'<a href="../{prev_a["slug"].split("/")[-1]}/" class="card"><span class="card__cta" style="margin-bottom: 0.5rem;">&larr; Previous article</span><h3 style="margin: 0;">{prev_a["title"]}</h3></a>')
        other_articles = f'<div class="cards" style="margin-top: 3rem;">{"".join(items)}</div>'

    return f"""
  <section class="page-hero">
    <div class="container">
      <div class="page-hero__inner">
        <div class="insight-meta">
          <span class="insight-meta__chip">{a['chip']}</span>
          <span>{a['date_human']}</span>
          <span class="insight-meta__sep">&middot;</span>
          <span>{a['read_time']}</span>
        </div>
        <h1>{a['title']}</h1>
        <p class="lead">{a['summary']}</p>
      </div>
    </div>
  </section>

  <section class="section">
    <div class="container">
      <article class="prose">
        {a['body']}
      </article>

      {other_articles}
    </div>
  </section>
"""


ARTICLE_MEDIA = {
    "proof-of-purchase-mechanics": (
        "assets/img/insights/proof-of-purchase-mechanics.svg",
        "Illustration comparing proof-of-purchase mechanics: receipts, batch codes and unique codes",
    ),
    "in-factory-printing-cheaper": (
        "assets/img/insights/in-factory-printing-cheaper.svg",
        "Illustration showing in-factory unique-code printing reducing costs versus legacy printing",
    ),
    "closed-loop-validation": (
        "assets/img/insights/closed-loop-validation.svg?v=2",
        "Illustration of closed-loop algorithmic validation without a master code database or lookup bottleneck",
    ),
    "outside-vs-inside-pack-code-copying": (
        "assets/img/insights/outside-vs-inside-pack-code-copying.svg",
        "Illustration of an optional audit check for an outside-pack code submission",
    ),
    "agile-digital-promotions": (
        "assets/img/insights/agile-digital-promotions.svg",
        "Illustration of agile digital promotions launching from already-coded packs",
    ),
    "beyond-promotions-five-uses": (
        "assets/img/insights/beyond-promotions-five-uses.svg",
        "Illustration of five business uses unlocked by per-pack unique codes",
    ),
}


def insight_media(slug_last: str, prefix="../"):
    src, alt = ARTICLE_MEDIA[slug_last]
    return f'<img src="{prefix}{src}" alt="{alt}" width="1200" height="675" loading="lazy" decoding="async">'


def insights_index_body(articles):
    if not articles:
        return ""
    featured = articles[0]
    others = articles[1:]

    feat_card = f"""
      <a href="{featured['slug'].split('/')[-1]}/" class="insight-card featured">
        <div class="insight-card__media">
          {insight_media(featured['slug'].split('/')[-1])}
        </div>
        <div class="insight-card__body">
          <div class="insight-meta">
            <span class="insight-meta__chip">{featured['chip']}</span>
            <span>{featured['date_human']}</span>
            <span class="insight-meta__sep">&middot;</span>
            <span>{featured['read_time']}</span>
          </div>
          <h3>{featured['title']}</h3>
          <p>{featured['desc']}</p>
          <span class="insight-card__more">Read article &rarr;</span>
        </div>
      </a>
    """

    other_cards = "".join(
        f"""
      <a href="{a['slug'].split('/')[-1]}/" class="insight-card">
        <div class="insight-card__media">
          {insight_media(a['slug'].split('/')[-1])}
        </div>
        <div class="insight-card__body">
          <div class="insight-meta">
            <span class="insight-meta__chip">{a['chip']}</span>
            <span>{a['date_human']}</span>
          </div>
          <h3>{a['title']}</h3>
          <p>{a['desc']}</p>
          <span class="insight-card__more">Read &rarr;</span>
        </div>
      </a>
        """ for a in others
    )

    return f"""
  <section class="section">
    <div class="container">
      <div class="page-hero__inner">
        <span class="eyebrow">Insights</span>
        <h1>Field notes on unique coding, in-factory print, and how brands actually use them.</h1>
        <p class="lead">Working notes on what we&rsquo;ve learned across hundreds of factory deployments and billions of codes &mdash; written for marketing, procurement and operations teams thinking through their own programmes.</p>
      </div>
    </div>
  </section>

  <section class="section section--soft">
    <div class="container">
      <div class="insight-grid">
        {feat_card}
        {other_cards}
      </div>
    </div>
  </section>
"""


# ---------- About / Contact ----------------------------------------------

ABOUT_BODY = """
  <section class="page-hero">
    <div class="container">
      <div class="page-hero__inner">
        <span class="eyebrow">About Hive IP</span>
        <h1>Unique coding for FMCG, end-to-end &mdash; and only that.</h1>
        <p class="lead">Hive IP Ltd is a UK-based company specialising in the generation, in-factory or supplier-supplied print, cloud validation, fraud monitoring and consumer support for unique codes. We&rsquo;ve been quietly running this category for years &mdash; including the largest in-factory deployment in European FMCG &mdash; and we don&rsquo;t do anything else.</p>
      </div>
    </div>
  </section>

  <section class="section">
    <div class="container">
      <div class="prose" style="max-width: 70ch;">
        <h2>What we do</h2>
        <p>Unique-coding is the whole company. We design and supply the in-factory hardware (the <abbr title="Automated Code Generator">ACG</abbr>), we run the cloud validation infrastructure, we build the fraud-monitoring systems, we operate the Consumer Support Panel for our customers&rsquo; teams, and we work directly with the agencies that build the consumer-facing experiences. <a href="../solution/">Read about the full solution &rarr;</a></p>

        <h2>Where we operate</h2>
        <p>Headquartered in the UK. ACGs running across customer factories in the UK, the Netherlands and Portugal. Validation infrastructure hosted on AWS. Customer programmes spanning multiple European markets. We work in English with brands and agencies across Europe; multi-language support for consumer-facing experiences is handled at the agency layer.</p>

        <h2>Who we work with</h2>
        <p>Our customers are FMCG brands &mdash; from large multinationals to category challengers &mdash; and the agencies they appoint to run their consumer programmes. We work with marketing teams, procurement teams, packaging operations, and brand-protection teams; the unique-coding stack touches all of them. <a href="../case-studies/">See selected case studies &rarr;</a></p>

        <h2>How we charge</h2>
        <p>We supply the ACG hardware at no charge into customer factories and bill only on the codes covered by an active promotional campaign &mdash; the codes on packs in market during the campaign window. Validation, fraud monitoring and consumer-support tooling are included. <a href="../our-model/">Read about our model &rarr;</a></p>

        <h2>How to talk to us</h2>
        <p>The shortest path is to email <a href="mailto:info@hiveip.co.uk">info@hiveip.co.uk</a>, or use the form on our <a href="../contact/">contact page</a>.</p>
      </div>
    </div>
  </section>
"""


CONTACT_BODY = """
  <section class="page-hero">
    <div class="container">
      <div class="page-hero__inner">
        <span class="eyebrow">Talk to us</span>
        <h1>Send us your details and we&rsquo;ll be in touch.</h1>
        <p class="lead">We respond to every enquiry from a real person. If your question is technical, commercial or strategic, we&rsquo;ll route it to the right person on our team.</p>
      </div>
    </div>
  </section>

  <section class="section">
    <div class="container">
      <div class="contact-grid">
        <form class="form"
              method="POST"
              action="https://formsubmit.co/info@hiveip.co.uk"
              data-form="contact">
          <input type="hidden" name="_subject" value="New Hive IP website enquiry">
          <input type="hidden" name="_template" value="table">
          <input type="hidden" name="_captcha" value="false">
          <input type="hidden" name="_next" value="https://hiveip.co.uk/contact/?sent=1">

          <div class="form__success" data-form-success hidden>
            <strong>Thanks, your enquiry has been sent.</strong>
            <span>We&rsquo;ll come back to you as soon as we can.</span>
          </div>

          <div class="form__row">
            <div class="form__field">
              <label for="contact-name">Your name <span class="req" aria-hidden="true">*</span></label>
              <input id="contact-name" name="name" type="text" required autocomplete="name">
            </div>
            <div class="form__field">
              <label for="contact-company">Company <span class="req" aria-hidden="true">*</span></label>
              <input id="contact-company" name="company" type="text" required autocomplete="organization">
            </div>
          </div>

          <div class="form__row">
            <div class="form__field">
              <label for="contact-email">Email <span class="req" aria-hidden="true">*</span></label>
              <input id="contact-email" name="email" type="email" required autocomplete="email">
            </div>
            <div class="form__field">
              <label for="contact-role">Your role</label>
              <input id="contact-role" name="role" type="text" autocomplete="organization-title" placeholder="e.g. Marketing Director, Procurement Lead">
            </div>
          </div>

          <div class="form__field">
            <label for="contact-topic">What's the conversation about?</label>
            <select id="contact-topic" name="topic">
              <option value="">Select an option (optional)</option>
              <option>Scoping a new unique-coding programme</option>
              <option>Costs and savings for our existing programme</option>
              <option>Technical / API integration question</option>
              <option>Case study or media enquiry</option>
              <option>Something else</option>
            </select>
          </div>

          <div class="form__field">
            <label for="contact-message">Tell us a little about your programme <span class="req" aria-hidden="true">*</span></label>
            <textarea id="contact-message" name="message" required placeholder="Annual pack volume, typical campaigns per year, current setup &mdash; whatever&rsquo;s on your mind. No need for detail at this stage."></textarea>
            <span class="form__hint">Anything you share is treated confidentially and used only to respond to your enquiry.</span>
          </div>

          <!-- Honeypot anti-spam (hidden from users) -->
          <div style="position:absolute; left:-9999px;" aria-hidden="true">
            <label for="contact-website">Your website (leave blank)</label>
            <input id="contact-website" name="_gotcha" type="text" tabindex="-1" autocomplete="off">
          </div>

          <div class="form__submit">
            <button class="btn btn--primary btn--lg" type="submit">
              Send enquiry
              <svg class="arrow" viewBox="0 0 16 16" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 8h10M9 4l4 4-4 4" stroke-linecap="round" stroke-linejoin="round"/></svg>
            </button>
            <p class="form__hint">Or email us directly.</p>
          </div>
        </form>

        <aside>
          <div class="contact-card" style="margin-bottom: 1.5rem;">
            <h3>Email</h3>
            <p style="margin: 0;"><a href="mailto:info@hiveip.co.uk">info@hiveip.co.uk</a></p>
            <p style="margin-top: 0.6rem; color: var(--mute); font-size: var(--fs-sm);">Goes directly to the Hive IP team.</p>
          </div>
          <div class="contact-card">
            <h3>Where we are</h3>
            <p style="margin: 0; color: var(--ink-soft);">We work with FMCG brands, their agencies and their packaging suppliers globally.</p>
          </div>
        </aside>
      </div>
    </div>
  </section>
"""

# ---------- Run -----------------------------------------------------------

def main():
    print("Generating Phase 4 pages...")

    # Insights index
    write("insights/index.html", page(
        depth=1,
        title="Insights — field notes on unique coding for FMCG — Hive IP",
        description="Field notes on unique coding, in-factory print, fraud audit options, marketing agility, and broader applications. Written for marketing, procurement and operations teams.",
        slug_path="insights",
        body_html=insights_index_body(ARTICLES),
        breadcrumbs=[("", "Home"), (None, "Insights")],
        current_nav_key="insights",
    ))

    # Insight articles
    for i, a in enumerate(ARTICLES):
        prev_a = ARTICLES[i - 1] if i > 0 else None
        next_a = ARTICLES[i + 1] if i + 1 < len(ARTICLES) else None
        slug_last = a["slug"].split("/")[-1]
        # Build schema separately to avoid f-string + backslash limitation
        title_esc = a["title"].replace('"', '\\"')
        desc_esc  = a["desc"].replace('"', '\\"')
        schema = (
            '\n  <script type="application/ld+json">\n'
            '  {\n'
            '    "@context": "https://schema.org",\n'
            '    "@type": "Article",\n'
            f'    "headline": "{title_esc}",\n'
            f'    "description": "{desc_esc}",\n'
            f'    "datePublished": "{a["date"]}",\n'
            '    "author": { "@type": "Organization", "name": "Hive IP" },\n'
            '    "publisher": {\n'
            '      "@type": "Organization",\n'
            '      "name": "Hive IP",\n'
            '      "logo": { "@type": "ImageObject", "url": "https://hiveip.co.uk/assets/img/logo/hive-logo.png" }\n'
            '    },\n'
            f'    "mainEntityOfPage": "https://hiveip.co.uk/{a["slug"]}/"\n'
            '  }\n'
            '  </script>'
        )
        write(f"{a['slug']}/index.html", page(
            depth=2,
            title=f"{a['title']} — Hive IP",
            description=a["desc"],
            slug_path=a["slug"],
            body_html=article_body(a, (prev_a, next_a)),
            breadcrumbs=[("", "Home"), ("insights/", "Insights"), (None, a["title"])],
            current_nav_key="insights",
            schema_extra=schema,
        ))

    # About
    write("about/index.html", page(
        depth=1,
        title="About Hive IP — unique-coding specialists for FMCG",
        description="Hive IP Ltd is a UK-based company specialising in unique coding for FMCG brands — generation, in-factory or supplier print, validation, fraud monitoring and consumer support, end-to-end.",
        slug_path="about",
        body_html=ABOUT_BODY,
        breadcrumbs=[("", "Home"), (None, "About")],
        current_nav_key="",  # no top-nav highlight (About lives in footer)
    ))

    # Contact
    write("contact/index.html", page(
        depth=1,
        title="Contact Hive IP — talk to us about your unique-coding programme",
        description="Send us your details or email info@hiveip.co.uk to talk about your unique-coding programme.",
        slug_path="contact",
        body_html=CONTACT_BODY,
        breadcrumbs=[("", "Home"), (None, "Contact")],
        current_nav_key="",
        show_final_phone=False,
    ))

    print("Done.")


if __name__ == "__main__":
    main()
